// <auto-generated />
using System;
using BillingService.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BillingService.Migrations
{
    [DbContext(typeof(BillingDatabaseContext))]
    [Migration("20200623233629_InitialMig")]
    partial class InitialMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BillingService.Models.sale", b =>
                {
                    b.Property<Guid>("saleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("billId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("productRefId")
                        .HasColumnType("uuid");

                    b.Property<long>("saleAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("saleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("saleTotalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("saleUnitPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("stockLeft")
                        .HasColumnType("bigint");

                    b.HasKey("saleId");

                    b.ToTable("sale");
                });
#pragma warning restore 612, 618
        }
    }
}
